### ISSUE TITLE
Nullpointer with v1.0.1 on the SearchView

### ISSUE THREAD

**Issue by Marc1510** [jgilfelt/chuck#11]
On the latest version when opening the notification I got the following crash:
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.triple.verstappen.dev, PID: 6720
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.setOnQueryTextListener(android.support.v7.widget.SearchView$OnQueryTextListener)' on a null object reference
                                                                             at com.readystatesoftware.chuck.internal.ui.TransactionListFragment.onCreateOptionsMenu(TransactionListFragment.java:107)
                                                                             at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2288)
                                                                             at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:2984)
                                                                             at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:328)
                                                                             at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:363)
                                                                             at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
                                                                             at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:335)
                                                                             at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
                                                                             at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
                                                                             at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by jgilfelt** [comment]
Are you using proguard? If so, add the following to your rules file:

```
-keep class android.support.v7.widget.SearchView { *; }
```

I'll get it added to the library's rules configuration in the next release.

**Comment by Marc1510** [comment]
I was indeed using proguard. Thanks for looking into it!
