### ISSUE TITLE
Android Kitkat Error

### ISSUE THREAD

**Issue by pasha14** [jgilfelt/chuck#28]
Hi,
First of all, I thank you for this library.
I got some issue on Android 4.4.x version. Here is the exception:
`FATAL EXCEPTION: main
                                                                Process: com.ross.android, PID: 9282
                                                                java.lang.RuntimeException: Unable to get provider com.readystatesoftware.chuck.internal.data.ChuckContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.readystatesoftware.chuck.internal.data.ChuckContentProvider" on path: DexPathList[[zip file "/data/app/com.ross.android-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.ross.android-1, /vendor/lib, /system/lib]]
                                                                    at android.app.ActivityThread.installProvider(ActivityThread.java:5060)
                                                                    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4631)
                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4571)
                                                                    at android.app.ActivityThread.access$1500(ActivityThread.java:155)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1406)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                    at android.os.Looper.loop(Looper.java:193)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5341)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:646)
                                                                    at dalvik.system.NativeStart.main(Native Method)
                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.readystatesoftware.chuck.internal.data.ChuckContentProvider" on path: DexPathList[[zip file "/data/app/com.ross.android-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.ross.android-1, /vendor/lib, /system/lib]]
                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                    at android.app.ActivityThread.installProvider(ActivityThread.java:5045)
                                                                    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4631) 
                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4571) 
                                                                    at android.app.ActivityThread.access$1500(ActivityThread.java:155) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1406) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                    at android.os.Looper.loop(Looper.java:193) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5341) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:646) 
                                                                    at dalvik.system.NativeStart.main(Native Method) `

Thanks any advice..

**Comment by pasha14** [comment]
These are my config:   
 project.extensions.add("buildToolsVersion", "25")
    project.extensions.add("compileSdkVersion", 25)
    project.extensions.add("minSdkVersion", 16)
    project.extensions.add("targetSdkVersion", 23)

**Comment by marlonlu** [comment]
close Android Studio Instant Run

**Comment by nethergrim** [comment]
I'm getting the same error, multidex is enabled, instant run turned off.
So it crashes only on api<21, when multidex is applied.

**Comment by nethergrim** [comment]
This helped me:

```
debug {
            multiDexEnabled true
            multiDexKeepFile file('multidex.keep')
}
```

Content of multidex.keep:

```
com/readystatesoftware/chuck/internal/data/ChuckContentProvider.class
com/readystatesoftware/chuck/internal/data/ChuckDbOpenHelper.class

```

**Comment by LloydBlv** [comment]
this issue happens when the multidex is enabled but the application class is not extended from MultidexApplication or Multidex.install is not called in onCreate()

**Comment by Shipaaaa** [comment]
I have the same problem because of the instant run.
