### ISSUE TITLE
Throw exception on api version < 21 

### ISSUE THREAD

**Issue by WeRockStar** [jgilfelt/chuck#45]
```
  Caused by: java.lang.NoClassDefFoundError: nl.qbusict.cupboard.Cupboard
                                                     at com.readystatesoftware.chuck.internal.data.ChuckDbOpenHelper.onCreate(ChuckDbOpenHelper.java:33)
                                                     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
                                                     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
                                                     at com.readystatesoftware.chuck.internal.data.ChuckContentProvider.insert(ChuckContentProvider.java:83)
```

**Comment by jgilfelt** [comment]
Possible duplicate of #28. Try adding affected classes to a `multiDexKeepFile` per [this comment](https://github.com/jgilfelt/chuck/issues/28#issuecomment-288978527).
