### ISSUE TITLE
NPE on NotificationHelper l94

### ISSUE THREAD

**Issue by fraynaud33** [jgilfelt/chuck#69]
Hello, I have a random crash on Android 7.0, with library com.readystatesoftware.chuck:library:1.1.0
FATAL EXCEPTION: OkHttp Dispatcher
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.readystatesoftware.chuck.internal.data.HttpTransaction.getNotificationText()' on a null object reference
    at com.readystatesoftware.chuck.internal.support.NotificationHelper.show(NotificationHelper.java:94)
    at com.readystatesoftware.chuck.ChuckInterceptor.create(ChuckInterceptor.java:228)
    at com.readystatesoftware.chuck.ChuckInterceptor.intercept(ChuckInterceptor.java:167)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:762)

**Comment by jkyeo** [comment]
The same problem with it.

- Android OS: 7.0

**Comment by Axrorxoja** [comment]
Same problem
