### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by LinXiaoTao** [jgilfelt/chuck#81]
Hello, This is the error message
``` text
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getLastPathSegment()' on a null object reference
at com.readystatesoftware.chuck.ChuckInterceptor.create(ChuckInterceptor.java:226)
	at com.readystatesoftware.chuck.ChuckInterceptor.intercept(ChuckInterceptor.java:167)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
```

**Comment by olivierperez** [comment]
Hi, Chuck seems to be abandonned. With Nicola we forked to maintain it.
Can you try with [Chucker](https://github.com/ChuckerTeam/chucker)? And tell us if you still have the issue.

If the issue is still there, do you have a project repository we can clone to reproduce it?
