### ISSUE TITLE
NPE when retrieving app name

### ISSUE THREAD

**Issue by jrodiz** [jgilfelt/chuck#83]
Process: com.neoris.pickup.am.sdb, PID: 29814
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.neoris.pickup.am.sdb/**com.readystatesoftware.chuck.internal.ui.MainActivity**}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     **Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
        at com.readystatesoftware.chuck.internal.ui.MainActivity.getApplicationName(MainActivity.java:50)
        at com.readystatesoftware.chuck.internal.ui.MainActivity.onCreate(MainActivity.java:34)**
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2018-12-20 13:38:30.800 1881-1948/? E/InputDispatcher: channel '63ce1f0 com.neoris.pickup.am.sdb/com.neoris.pickup.features.quarry.presentation.QuarryActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2018-12-20 13:38:31.203 14507-29399/? E/ctxmgr: [ProducerStatusImpl]updateStateForNewContextData: inactive, contextName=7

**Comment by cortinico** [comment]
Hey @jrodiz 
Side note: Looks like this project is no longer maintained.
We forked it and we're rewriting it in Kotlin/Room (modern stuff, etc.) here:

https://github.com/ChuckerTeam/chucker
You can maybe try chucker and see if is still crashing. If so, we can help you fix the issue :)
