### ISSUE TITLE
NullPointerException at HttpTransaction.getNotificationText()

### ISSUE THREAD

**Issue by a-reznic** [jgilfelt/chuck#99]
```
E/AbsApiWorker$execute2: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.readystatesoftware.chuck.internal.data.HttpTransaction.getNotificationText()' on a null object reference
E/AbsApiWorker$execute2:     at com.readystatesoftware.chuck.internal.support.NotificationHelper.show(NotificationHelper.java:96)
E/AbsApiWorker$execute2:     at com.readystatesoftware.chuck.ChuckInterceptor.create(ChuckInterceptor.java:228)
E/AbsApiWorker$execute2:     at com.readystatesoftware.chuck.ChuckInterceptor.intercept(ChuckInterceptor.java:167)
E/AbsApiWorker$execute2:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/AbsApiWorker$execute2:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/AbsApiWorker$execute2:     at com.isidroid.a18.rest.Api$build$interceptor$1.intercept(Api.kt:51)
E/AbsApiWorker$execute2:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/AbsApiWorker$execute2:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/AbsApiWorker$execute2:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
E/AbsApiWorker$execute2:     at okhttp3.RealCall.execute(RealCall.java:92)
E/AbsApiWorker$execute2:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
E/AbsApiWorker$execute2:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
E/AbsApiWorker$execute2:     at io.reactivex.Observable.subscribe(Observable.java:12267)
E/AbsApiWorker$execute2:     at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:29)
E/AbsApiWorker$execute2:     at io.reactivex.Flowable.subscribe(Flowable.java:14827)
E/AbsApiWorker$execute2:     at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:32)
E/AbsApiWorker$execute2:     at io.reactivex.Flowable.subscribe(Flowable.java:14827)
E/AbsApiWorker$execute2:     at io.reactivex.Flowable.subscribe(Flowable.java:14774)
E/AbsApiWorker$execute2:     at io.reactivex.Flowable.subscribeWith(Flowable.java:14883)
E/AbsApiWorker$execute2:     at io.reactivex.Flowable.toFuture(Flowable.java:5970)
```

**Comment by Ashok-Varma** [comment]
Hi @a-reznic , This project is not maintained. You can try one of these forks

1. [Chucker](https://github.com/ChuckerTeam/chucker) - chuck + supports debug logs ..etc
2. [Gander](https://github.com/Ashok-Varma/Gander) - lean version of chuck
